export const ImagesResource = {
  SLIDE_SLIDE1: require('./slide/slide-1.jpg'),
  SLIDE_SLIDE2: require('./slide/slide-2.jpg'),
  SLIDE_SLIDE3: require('./slide/slide-3.jpg'),

  CLIENTS_CLIENT1: require('./clients/client-1.png'),
  CLIENTS_CLIENT2: require('./clients/client-2.png'),
  CLIENTS_CLIENT3: require('./clients/client-3.png'),
  CLIENTS_CLIENT4: require('./clients/client-4.png'),
  CLIENTS_CLIENT5: require('./clients/client-5.png'),
  CLIENTS_CLIENT6: require('./clients/client-6.png'),

  PORTFOLIO_PORTFOLIO1: require('./portfolio/portfolio-1.jpg'),
  PORTFOLIO_PORTFOLIO2: require('./portfolio/portfolio-2.jpg'),
  PORTFOLIO_PORTFOLIO3: require('./portfolio/portfolio-3.jpg'),
  PORTFOLIO_PORTFOLIO4: require('./portfolio/portfolio-4.jpg'),
  PORTFOLIO_PORTFOLIO5: require('./portfolio/portfolio-5.jpg'),
  PORTFOLIO_PORTFOLIO6: require('./portfolio/portfolio-6.jpg'),
  PORTFOLIO_PORTFOLIO7: require('./portfolio/portfolio-7.jpg'),
  PORTFOLIO_PORTFOLIO8: require('./portfolio/portfolio-8.jpg'),
  PORTFOLIO_PORTFOLIO9: require('./portfolio/portfolio-9.jpg'),
  PORTFOLIO_PORTFOLIO_DETAILS1: require('./portfolio/portfolio-details-1.jpg'),
  PORTFOLIO_PORTFOLIO_DETAILS2: require('./portfolio/portfolio-details-2.jpg'),
  PORTFOLIO_PORTFOLIO_DETAILS3: require('./portfolio/portfolio-details-3.jpg'),

  BLOG_BLOG1: require('./blog/blog-1.jpg'),
  BLOG_BLOG2: require('./blog/blog-2.jpg'),
  BLOG_BLOG3: require('./blog/blog-3.jpg'),
  BLOG_BLOG4: require('./blog/blog-4.jpg'),

  FEATURES_1: require('./features-1.png'),
  FEATURES_2: require('./features-2.png'),
  FEATURES_3: require('./features-3.png'),
  FEATURES_4: require('./features-4.png'),
  FEATURES_5: require('./features-5.png'),

  TEAM_TEAM_1: require('./team/team-1.jpg'),
  TEAM_TEAM_2: require('./team/team-2.jpg'),
  TEAM_TEAM_3: require('./team/team-3.jpg'),
  TEAM_TEAM_4: require('./team/team-4.jpg'),
};
